-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
-- vim.lsp.enable({ "pyright" })
-- vim.lsp.enable("pyrefly")
-- Default options:

-- vim.lsp.enable("solargraph", true)
-- vim.lsp.enable("bashls", true)
-- vim.lsp.enable("pyrefly", true)
-- vim.lsp.enable("gopls", true)

-- pwsh-lsp
-- local on_attach = function(client, bufnr)
-- 	-- Enable completion triggered by <c-x><c-o>
-- 	vim.api.nvim_buf_set_option(bufnr, "omnifunc", "v:lua.vim.lsp.omnifunc")
--
-- 	local bufopts = { noremap = true, silent = true, buffer = bufnr }
-- 	vim.keymap.set("n", "<C-k>", vim.lsp.buf.signature_help, bufopts)
-- 	vim.keymap.set("n", "gD", vim.lsp.buf.declaration, bufopts)
-- 	vim.keymap.set("n", "gd", vim.lsp.buf.definition, bufopts)
-- 	vim.keymap.set("n", "gi", vim.lsp.buf.implementation, bufopts)
-- 	vim.keymap.set("n", "gr", vim.lsp.buf.references, bufopts)
-- 	vim.keymap.set("n", "K", vim.lsp.buf.hover, bufopts)
-- 	vim.keymap.set("n", "<Leader>ca", vim.lsp.buf.code_action, bufopts)
-- 	vim.keymap.set("n", "<Leader>f", function()
-- 		vim.lsp.buf.format({ async = true })
-- 	end, bufopts)
-- 	vim.keymap.set("n", "<Leader>rn", vim.lsp.buf.rename, bufopts)
-- 	vim.keymap.set("n", "<Leader>td", vim.lsp.buf.type_definition, bufopts)
-- end
-- local bundle_path = "/Users/nikodem/library/zed-pwsh-lsp/PowerShellEditorServices"
-- require("lspconfig")["powershell_es"].setup({
-- 	bundle_path = bundle_path,
-- 	on_attach = on_attach,
-- })
-- pyright-lsp
-- require("lspconfig").pyright.setup({
-- 	settings = {
-- 		python = {
-- 			analysis = {
-- 				-- typeCheckingMode = "strict",
-- 				useLibraryCodeForTypes = true,
-- 				diagnosticMode = "workspace",
-- 			},
-- 		},
-- 	},
-- })
